export const RENDER_COINS = 'RENDER_COINS'
export const RENDER_REFRESHED_COINS = 'RENDER_REFRESHED_COINS'
export const RENDER_CURRENT_COIN = 'RENDER_CURRENT_COIN'
export const RESET_COINS = 'RESET_COINS'